# Generated by Django 5.2.12 on 2026-03-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexaoagenda',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
