# Generated by Django 5.2.12 on 2026-03-17 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_tarefacompleta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='telefone',
        ),
        migrations.AddField(
            model_name='aluno',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='alunos', to=settings.AUTH_USER_MODEL, verbose_name='Usuários vinculados'),
        ),
    ]
