# Generated by Django 5.2.12 on 2026-04-16 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0006_aluno_add_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendaevento",
            name="inicio",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agendaevento",
            name="tem_anexo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agendaevento",
            name="termino",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agendaevento",
            name="data",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agendaevento",
            name="datas",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="agendaevento",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="agendaevento",
            name="dia",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="agendaevento",
            name="tipo",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="agendaevento",
            name="turma",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agenda.turma",
            ),
        ),
        migrations.AddIndex(
            model_name="agendaevento",
            index=models.Index(fields=["data"], name="agenda_agen_data_aa1ed7_idx"),
        ),
        migrations.AddIndex(
            model_name="agendaevento",
            index=models.Index(fields=["inicio"], name="agenda_agen_inicio_0e8f3c_idx"),
        ),
        migrations.AddIndex(
            model_name="agendaevento",
            index=models.Index(fields=["turma"], name="agenda_agen_turma_i_541c38_idx"),
        ),
    ]
