# Generated by Django 5.2.12 on 2026-04-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0008_tarefacompleta_add_visivel"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendaevento",
            name="url_anexo",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
    ]
