# Generated by Django 5.2.12 on 2026-04-17 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0009_add_url_anexo_to_agendaevento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dias", models.CharField(max_length=20, verbose_name="Dia da semana")),
                ("ordem", models.IntegerField(default=0, verbose_name="Ordem")),
            ],
            options={
                "verbose_name": "Dia",
                "verbose_name_plural": "Dias",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_materia",
                    models.CharField(max_length=100, verbose_name="Matéria"),
                ),
            ],
            options={
                "verbose_name": "Matéria",
                "verbose_name_plural": "Matérias",
                "ordering": ["nome_materia"],
            },
        ),
        migrations.CreateModel(
            name="OrdemHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordem",
                    models.CharField(max_length=20, verbose_name="Ordem do horário"),
                ),
            ],
            options={
                "verbose_name": "Ordem de Horário",
                "verbose_name_plural": "Ordens de Horário",
            },
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_livro",
                    models.CharField(max_length=100, verbose_name="Nome do livro"),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livros",
                        to="agenda.escola",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livros",
                        to="agenda.materia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livro",
                "verbose_name_plural": "Livros",
                "ordering": ["nome_livro"],
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_professor",
                    models.CharField(max_length=100, verbose_name="Nome"),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professores",
                        to="agenda.escola",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professores",
                        to="agenda.materia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Professor",
                "verbose_name_plural": "Professores",
                "ordering": ["nome_professor"],
            },
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="agenda.dias",
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="agenda.escola",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="agenda.turma",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="agenda.materia",
                    ),
                ),
                (
                    "ordem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="agenda.ordemhorario",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="agenda.professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horário",
                "verbose_name_plural": "Horários",
                "ordering": ["turma", "dia__ordem", "ordem"],
            },
        ),
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conteudo",
                    models.TextField(blank=True, verbose_name="Conteúdo ministrado"),
                ),
                (
                    "data_aula",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da aula"
                    ),
                ),
                ("dever", models.TextField(blank=True, verbose_name="Dever de casa")),
                (
                    "data_entrega",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de entrega"
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, verbose_name="Observação geral"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas",
                        to="agenda.escola",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas",
                        to="agenda.turma",
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aulas",
                        to="agenda.livro",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas",
                        to="agenda.materia",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas",
                        to="agenda.professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
                "ordering": ["-data_aula", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="DiarioAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "presente",
                    models.BooleanField(default=True, verbose_name="Presente"),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, verbose_name="Observação individual"),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diario",
                        to="agenda.aluno",
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diario",
                        to="agenda.aula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro do Diário",
                "verbose_name_plural": "Registros do Diário",
                "unique_together": {("aula", "aluno")},
            },
        ),
    ]
