# Generated by Django 5.2.12 on 2026-04-17 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0010_add_diario_modelos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conexaoagenda",
            name="turma",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="agenda.turma"
            ),
        ),
    ]
