# Generated by Django 5.2.12 on 2026-04-22 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_populate_dias_ordemhorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaevento',
            name='aula',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento_espelho', to='agenda.aula'),
        ),
        migrations.AddField(
            model_name='agendaevento',
            name='conteudo',
            field=models.TextField(blank=True, verbose_name='Conteúdo ministrado'),
        ),
        migrations.AddField(
            model_name='agendaevento',
            name='data_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Data de entrega'),
        ),
        migrations.AddField(
            model_name='agendaevento',
            name='dever',
            field=models.TextField(blank=True, verbose_name='Dever de casa'),
        ),
        migrations.AddField(
            model_name='agendaevento',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='agenda.escola'),
        ),
        migrations.AddField(
            model_name='agendaevento',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='agenda.livro'),
        ),
        migrations.AddField(
            model_name='agendaevento',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='agenda.materia'),
        ),
        migrations.AddField(
            model_name='agendaevento',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação geral'),
        ),
        migrations.AddField(
            model_name='agendaevento',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='agenda.professor'),
        ),
    ]
