# Generated by Django 5.2.12 on 2026-04-22 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_agendaevento_aula_agendaevento_conteudo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('aluno', 'Aluno'), ('responsavel', 'Responsável'), ('professor', 'Professor'), ('coordenador', 'Coordenador'), ('admin_escola', 'Administrador da Escola'), ('superadmin', 'Super-admin')], default='responsavel', max_length=20)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis', to='agenda.escola', verbose_name='Escola padrão')),
                ('escolas_extras', models.ManyToManyField(blank=True, help_text='Outras escolas que este usuário pode acessar (multi-unidade).', related_name='perfis_extras', to='agenda.escola')),
                ('professor_vinculado', models.ForeignKey(blank=True, help_text='Quando preenchido, formulários já vêm com este professor selecionado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_vinculados', to='agenda.professor')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
            },
        ),
    ]
