# Generated by Django 5.2.12 on 2026-04-22 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='agenda.materia'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='agenda.professor'),
        ),
    ]
