# Generated by Django 5.2.12 on 2026-04-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_alter_horario_materia_alter_horario_professor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['turma', 'dia__ordem', 'ordem__posicao'], 'verbose_name': 'Horário', 'verbose_name_plural': 'Horários'},
        ),
        migrations.AlterModelOptions(
            name='ordemhorario',
            options={'ordering': ['posicao', 'id'], 'verbose_name': 'Ordem de Horário', 'verbose_name_plural': 'Ordens de Horário'},
        ),
        migrations.AddField(
            model_name='ordemhorario',
            name='inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Início'),
        ),
        migrations.AddField(
            model_name='ordemhorario',
            name='posicao',
            field=models.PositiveIntegerField(default=0, verbose_name='Posição'),
        ),
        migrations.AddField(
            model_name='ordemhorario',
            name='termino',
            field=models.TimeField(blank=True, null=True, verbose_name='Término'),
        ),
    ]
