# Generated by Django 5.2.12 on 2026-04-23 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_alter_horario_options_alter_ordemhorario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Início')),
                ('hora_fim', models.TimeField(verbose_name='Término')),
                ('sala', models.CharField(max_length=30, verbose_name='Sala')),
                ('nivel_ensino', models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio')], default='fundamental', max_length=20, verbose_name='Nível de ensino')),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorias', to='agenda.dias', verbose_name='Dia da semana')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorias', to='agenda.escola')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorias', to='agenda.materia', verbose_name='Componente curricular')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorias', to='agenda.professor', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Monitoria',
                'verbose_name_plural': 'Monitorias',
                'ordering': ['escola', 'dia__ordem', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ProfessorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Início do vínculo')),
                ('data_fim', models.DateField(blank=True, help_text='Deixe em branco enquanto o vínculo estiver ativo.', null=True, verbose_name='Fim do vínculo')),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_usuarios', to='agenda.professor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo Professor ↔ Usuário',
                'verbose_name_plural': 'Vínculos Professor ↔ Usuário',
                'ordering': ['-ativo', '-data_inicio'],
            },
        ),
    ]
