# Generated by Django 5.2.12 on 2026-04-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_monitoria_professorusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoria',
            name='nivel_ensino',
            field=models.CharField(blank=True, default='', help_text='Texto livre. Ex.: Ensino Fundamental, Ensino Médio, 9º ano...', max_length=80, verbose_name='Nível de ensino'),
        ),
    ]
