# Generated by Django 5.2.12 on 2026-04-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0020_ordemhorario_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='logo',
            field=models.ImageField(blank=True, help_text='Imagem usada no cabeçalho de relatórios PDF.', null=True, upload_to='escolas/logos/', verbose_name='Logo da escola'),
        ),
    ]
