# Generated by Django 5.2.12 on 2026-04-27 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0021_escola_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemhorario',
            options={'ordering': ['escola__nome_escola', 'turno', 'posicao', 'id'], 'verbose_name': 'Ordem de Horário', 'verbose_name_plural': 'Ordens de Horário'},
        ),
        migrations.AddField(
            model_name='ordemhorario',
            name='escola',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para período GLOBAL (visível em todas as escolas). Apenas super-administrador pode gerenciar períodos globais.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_horario', to='agenda.escola', verbose_name='Escola'),
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criar_usuario', 'Criação de usuário'), ('excluir_usuario', 'Exclusão de usuário'), ('mudar_papel', 'Mudança de papel'), ('excluir_escola', 'Exclusão de escola'), ('resetar_senha', 'Reset de senha'), ('desativar_usuario', 'Desativação de usuário')], max_length=30)),
                ('descricao', models.CharField(blank=True, help_text="Texto livre descrevendo a ação (ex.: 'Excluiu usuário joao').", max_length=255)),
                ('recurso', models.CharField(blank=True, help_text="Tipo do recurso afetado (ex.: 'User', 'Escola').", max_length=50)),
                ('recurso_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Quem executou')),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to='agenda.escola')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['-criado_em'], name='agenda_loga_criado__0593e7_idx'), models.Index(fields=['acao'], name='agenda_loga_acao_346a87_idx')],
            },
        ),
    ]
