# Generated by Django 5.2.12 on 2026-03-13 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=20)),
                ('mensagem', models.TextField()),
                ('sucesso', models.BooleanField(default=False)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instancia', models.CharField(max_length=100, unique=True)),
                ('numero_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('creating', 'Criando'), ('qr_ready', 'QR pronto'), ('connected', 'Conectado'), ('disconnected', 'Desconectado'), ('error', 'Erro')], default='creating', max_length=20)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MensagemWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_destino', models.CharField(max_length=20)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(default='enviado', max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.whatsappinstance')),
            ],
        ),
    ]
